name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/binance-candles
            git pull origin main
            npm install --production
            pm2 restart taapi-app || pm2 start npm --name "taapi-app" -- run start
